DEMO="Red Hat PAM 7 - Order IT Hardware Demo"
AUTHORS="Red Hat"
PROJECT="git@github.com:jbossdemocentral/rhpam7-order-it-hw-demo.git"
PRODUCT="Red Hat Process Automation Manager"
TARGET=./target
JBOSS_HOME=$TARGET/jboss-eap-7.2
SERVER_DIR=$JBOSS_HOME/standalone/deployments
SERVER_CONF=$JBOSS_HOME/standalone/configuration/
SERVER_BIN=$JBOSS_HOME/bin
SRC_DIR=./installs
SUPPORT_DIR=./support
PAM_VERSION=7.7.0.GA
PAM_BUSINESS_CENTRAL=rhpam-$PAM_VERSION-business-central-eap7-deployable.zip
PAM_KIE_SERVER=rhpam-$PAM_VERSION-kie-server-ee8.zip
EAP=jboss-eap-7.2.0.zip
#EAP_PATCH=jboss-eap-6.4.7-patch.zip
VERSION=7.7
PROJECT_GIT_REPO=https://github.com/jbossdemocentral/rhpam7-order-it-hw-demo-repo
PROJECT_GIT_REPO_NAME=examples-rhpam7-order-it-hw-demo-repo.git
NIOGIT_PROJECT_GIT_REPO="MySpace/$PROJECT_GIT_REPO_NAME"
