---
apiVersion: v1
kind: Template
labels:
  template: rhpam711-businesscental-openshift-with-users
  group: xpaas
metadata:
  name: rhpam711-businesscentral-openshift-with-users
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rhpam711-businesscentral-openshift-with-users
    annotations:
    labels:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: rhpam711-businesscentral-openshift-with-users
    annotations:
      description: Builds Red Hat Process Automation Manager Business Central OpenShift image with additional users.
    labels:
      name: rhpam711-businesscentral-openshift-with-users
      app: rhpam711-businesscentral-openshift-with-users
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rhpam711-businesscentral-openshift-with-users:latest
    source:
      contextDir: ${DOCKERFILE_CONTEXT}
      git:
        uri: ${DOCKERFILE_REPOSITORY}
        ref: ${DOCKERFILE_REF}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhpam-businesscentral-rhel8:7.11.0
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: The directory in the git repository containing the Dockerfile.
  name: DOCKERFILE_CONTEXT
  required: true
- description: The git repository containing the Dockerfile
  name: DOCKERFILE_REPOSITORY
  required: true
- description: The git branch containing the Dockerfile
  name: DOCKERFILE_REF
  required: true
  default: master
